# Generated by Django 3.0.7 on 2020-06-30 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpttapp', '0002_auto_20200630_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='level',
            new_name='mptt_level',
        ),
    ]
